//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addset
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<bool> systemset { get; set; }
        public Nullable<bool> passengermanager { get; set; }
        public Nullable<bool> ticketmanager { get; set; }
        public Nullable<bool> ticketpurchage { get; set; }
        public Nullable<bool> systemsearch { get; set; }
    }
}
