//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linkman
    {
        public int linkmanID { get; set; }
        public Nullable<int> userID { get; set; }
        public string linkmanName { get; set; }
        public string sex { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> paperworkTypeID { get; set; }
        public string paperworkNumber { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string chekestate { get; set; }
        public string phonenumber { get; set; }
        public string fixedphone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public Nullable<int> ticketTypeID { get; set; }
    }
}
