//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonstopView
    {
        public int nonstopViewID { get; set; }
        public string Type { get; set; }
        public string StartStation { get; set; }
        public string EndStation { get; set; }
        public string RouteID { get; set; }
        public Nullable<int> StopCount { get; set; }
        public Nullable<int> KM { get; set; }
        public string D_Time { get; set; }
        public string A_Time { get; set; }
    }
}
