//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public string orderNum { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
        public Nullable<System.DateTime> rideDate { get; set; }
        public Nullable<bool> ifPaid { get; set; }
        public Nullable<bool> ifCancel { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
