//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outlet
    {
        public int OutletID { get; set; }
        public string OutleName { get; set; }
        public string address { get; set; }
        public string businessHours { get; set; }
        public Nullable<int> windownumber { get; set; }
        public Nullable<int> provinceID { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> townID { get; set; }
    }
}
