//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pinyin
    {
        public int ID { get; set; }
        public string Station { get; set; }
        public string Shortcode { get; set; }
        public string FullCode { get; set; }
        public string Province { get; set; }
        public string ProPinyin { get; set; }
        public Nullable<int> Call { get; set; }
    }
}
