//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returnticket
    {
        public int returnticketID { get; set; }
        public string returnNumber { get; set; }
        public Nullable<int> orderDetailID { get; set; }
        public Nullable<int> trainID { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<decimal> returnMoney { get; set; }
        public Nullable<decimal> fee { get; set; }
    }
}
