//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyTicket.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentID { get; set; }
        public Nullable<int> linkmanID { get; set; }
        public Nullable<int> provinceID { get; set; }
        public string schoolName { get; set; }
        public string department { get; set; }
        public string @class { get; set; }
        public string studentNumber { get; set; }
        public Nullable<int> lengthOfschooling { get; set; }
        public string yearIn { get; set; }
        public string cardNumber { get; set; }
        public string interval { get; set; }
    }
}
